# Generated by Django 4.0.4 on 2022-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['name', 'email', 'phone_number', 'message']},
        ),
        migrations.AddField(
            model_name='contato',
            name='message',
            field=models.TextField(default='No Message'),
            preserve_default=False,
        ),
    ]
