# Generated by Django 4.0.4 on 2022-07-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0002_alter_contact_options_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
