# Generated by Django 4.0.4 on 2022-07-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0003_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('EP', 'Em processo'), ('C', 'Contatado')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
