# Generated by Django 4.0.4 on 2022-07-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0004_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('EP', 'Em processo'), ('C', 'Contatado')], default='', max_length=2),
        ),
    ]
