# Generated by Django 4.0.4 on 2022-07-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0005_alter_contato_message_alter_contato_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='status',
            new_name='status_field',
        ),
    ]
