# Generated by Django 4.0.4 on 2022-07-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0008_alter_contato_email_alter_contato_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='contact_date',
            field=models.DateField(auto_now=True, verbose_name='Data de contato'),
        ),
    ]
