# Generated by Django 4.0.4 on 2022-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0010_alter_contato_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Número de telefone'),
        ),
    ]
