# Generated by Django 4.0.4 on 2022-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0011_alter_contato_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['name', 'email', 'phone_number', 'event_date', 'guests_number']},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='message',
        ),
        migrations.AddField(
            model_name='contato',
            name='event_date',
            field=models.DateField(default="1111-11-11", verbose_name='Data do evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='guests_number',
            field=models.BigIntegerField(default=1, verbose_name='Número de convidados'),
            preserve_default=False,
        ),
    ]
